import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const component = (name: string) => readFileSync(new URL(`../src/components/${name}.tsx`, import.meta.url), 'utf8')
const apartment = component('ApartmentExplorer')
const building = component('BuildingExplorer')
const buildingScene = component('BuildingScene')
const buildingContext = component('BuildingContext')
const solar = component('SolarControls')
const site = readFileSync(new URL('../src/data/building-site.ts', import.meta.url), 'utf8')

test('T3 apartment controls retain their layer and room-navigation meanings', () => {
  assert.match(apartment, /checked=\{cutaway\} onChange=\{event => setCutaway/)
  assert.match(apartment, /checked=\{showFixtures\} onChange=\{event => setShowFixtures/)
  assert.match(apartment, /checked=\{showLabels\} onChange=\{event => setShowLabels/)
  assert.match(apartment, /setPanel\('sun'\)/)
  assert.match(apartment, /setPanel\('rooms'\)/)
  assert.match(apartment, /setPanel\('assets'\)/)
  assert.match(apartment, /focusRoom\(room\.id\)/)
  assert.match(apartment, /focusRoom\(currentFixtures\.find/)
  assert.match(apartment, /setShowFixtures\(true\)/)
})

test('T3 solar controls retain date, seasons, scrubber/play, solar readings, and daily chart', () => {
  assert.match(solar, /id="solar-date"/)
  assert.match(solar, /solar\.spring.*03-20/)
  assert.match(solar, /solar\.summer.*06-21/)
  assert.match(solar, /solar\.autumn.*09-22/)
  assert.match(solar, /solar\.winter.*12-21/)
  assert.match(solar, /id="solar-time-slider"/)
  assert.match(solar, /t\('solar\.playDay'\)/)
  assert.match(solar, /locationLabel = 'Quimper'/)
  assert.match(solar, /hemisphere === 'north' \? northernSeasons : southernSeasons/)
  assert.match(solar, /astronomicalOnly \? 'solar\.astronomicalOnlyDescription' : 'solar\.daylightDescription'/)
  assert.match(solar, /timeZone\}/)
  assert.match(solar, /solar\.altitude/)
  assert.match(solar, /solar\.azimuth/)
  assert.match(solar, /solar\.dayPathTitle/)
  assert.match(solar, /solar\.sunrise/)
  assert.match(solar, /solar\.sunset/)
})

test('T3 building view keeps whole/floor/interior and perspective/plan/reset camera controls', () => {
  assert.match(building, /building\.wholeBuilding/)
  assert.match(building, /building\.floorCut/)
  assert.match(building, /building\.interior/)
  assert.match(building, /resetView\('3d'\)/)
  assert.match(building, /resetView\('top'\)/)
  assert.match(building, /building\.neighbors/)
  assert.match(building, /building\.solarOrbit/)
  assert.match(building, /building\.coordinates/)
  assert.match(building, /BUILDING_SITE\.latitude/)
  assert.match(building, /BUILDING_SITE\.longitude/)
  assert.match(building, /BUILDING_SITE\.timeZone/)
})

test('Building and sun keeps the moving solar orbit, geolocation, context buildings, and labels', () => {
  assert.match(building, /<BuildingScene instant=\{instant\} sun=\{sun\} showNeighbors=\{showNeighbors\} showSunPath=\{showSunPath\} showLabels=\{showLabels\}/)
  assert.match(buildingScene, /function SolarOrbit\(\{ instant, sun \}: Pick/)
  assert.match(buildingScene, /getSolarDay\(date, BUILDING_SITE\.latitude, BUILDING_SITE\.longitude, BUILDING_SITE\.timeZone\)/)
  assert.match(buildingScene, /<mesh position=\{sunPoint\}/)
  assert.match(buildingScene, /sun\.direction\.map\(n => n \* 450\)/)
  assert.match(buildingScene, /<BuildingContext cutaway=\{cutaway\} showNeighbors=\{showNeighbors\}/)
  assert.match(buildingScene, /<SiteGround showRoads=\{showNeighbors\} \/>/)
  assert.match(buildingContext, /showRoads && <Boxes boxes=\{roads\} color="#c4c7bf" castShadow=\{false\} \/>/)
  assert.match(buildingScene, /building\.north/)
  assert.match(buildingScene, /building\.apartmentLabel/)
  assert.match(buildingScene, /building\.sunLabel/)
  assert.match(site, /latitude/)
  assert.match(site, /longitude/)
  assert.match(site, /"timeZone": "Europe\/Paris"/)
})
